apiVersion: apps/v1
kind: Deployment
metadata:
  name: license-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: license-api
  template:
    metadata:
      labels:
        app: license-api
    spec:
      containers:
        - name: license-api
          image: license-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_SERVER
              value: "license-db"
            - name: POSTGRES_PORT
              value: "5432"
            - name: CLIENT_DB_SERVER
              value: "client-db"
            - name: CLIENT_DB_PORT
              value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: license-api
spec:
  type: ClusterIP
  selector:
    app: license-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
